### ISSUE TITLE
HpFeeds auth logging crashes

### ISSUE THREAD

**Issue by kuax** [johnnykv/heralding#123]
Steps to replicate:

1. Enable HpFeeds logging (in my case HpFeeds only)
2. Run heralding
3. Make a login attempt through HTTP (or probably every other protocol)

heralding crashes giving this log:

```
2019-09-17 12:42:55,963 (heralding.misc.common) Stopping because <Future finished exception=TypeError('Object of type datetime is not JSON serializable')> died: Object of type datetime is not JSON serializable
```

The problem is the [session.py](https://github.com/johnnykv/heralding/blob/master/heralding/misc/session.py) file:

- [line 75](https://github.com/johnnykv/heralding/blob/master/heralding/misc/session.py#L75) the timestamp is a datetime object
- [line 93](https://github.com/johnnykv/heralding/blob/master/heralding/misc/session.py#L93) the entry is sent as is to the ReportingRelay
- only in [line 97](https://github.com/johnnykv/heralding/blob/master/heralding/misc/session.py#L97) is the timestamp converted to a string

thus the JSON serializer fails.

Not sure why the conversion to string is done only after logging to the ReportingRelay? Simply doing it straightaway solves the issue 👍

**Comment by johnnykv** [comment]
@kuax Just pushed a fix to master - got any time to test if it works?
(our automated test case for HPfeeds is very very limited :-) )

**Comment by johnnykv** [comment]
Closed since no feedback from author.
