### ISSUE TITLE
SSH won't start

### ISSUE THREAD

**Issue by haroldBarthel** [johnnykv/heralding#128]
hi

I tried out heralding today on a CentOS system. After going through the setup I tried to start it. I ran into a problem with SSH:

2020-01-01 16:02:21,460 (heralding.honeypot) Could not start SSH server on port 22. Error: prepare() got an unexpected keyword argument 'loop'

Although port 22 was not in use, I tried changing the port for SSH anyway:

2020-01-01 16:10:40,053 (heralding.honeypot) Could not start SSH server on port 22222. Error: prepare() got an unexpected keyword argument 'loop'

If I disable SSH 
i.e.,
  ssh:
    enabled: false

then heralding seems to start, and I see open ports for the other services.

Any idea what the root cause might be?

**Comment by t3chn0m4g3** [comment]
@johnnykv Same problem here:
`heralding    | 2020-01-02 15:23:27,807 (heralding.honeypot) Could not start SSH server on port 22. Error: prepare() got an unexpected keyword argument 'loop'`

Python version is 3.7.5.

**Comment by t3chn0m4g3** [comment]
Pinning `asyncssh==1.18.0` fixes it, however this seems only a temp solution, why I do not PR this 😃

**Comment by haroldBarthel** [comment]
Thanks for the responses.

CentOS 7.7 has an older version of python3, but today I installed 3.7.5 just to try it. I still get the same error.
I don't know how to pin asyncssh==1.18.0, so I haven't tried that. If you could please clarify how I can apply that workaround I will try it.

**Comment by t3chn0m4g3** [comment]
Just adjust the `requirements.txt` accordingly.

**Comment by haroldBarthel** [comment]
thanks, I was able to start it now.
