### ISSUE TITLE
Fix RDP implementation

### ISSUE THREAD

**Issue by johnnykv** [johnnykv/heralding#144]
The RDP implementation is broken. Hydra cannot bruteforce and the test case is failing.

Might be relates to TLS version.

@mimura1133 gave a potential hint in regards to root cause: https://github.com/johnnykv/heralding/pull/142#issuecomment-743681914

**Comment by t3chn0m4g3** [comment]
Any update on this?

**Comment by t3chn0m4g3** [comment]
Thank you!
