### ISSUE TITLE
What is the credentials for localhost:8080?? and where to find the logs?

### ISSUE THREAD

**Issue by amannayyar1** [johnnykv/heralding#148]
Hello everyone,

I have two questions and i am quite new to all of this, I have set up the docker version on ubuntu 18.04 and it has been installed correctly. 
Where do i find the credentials for the localhost login as i cannot access it as i do not know the details.
and where is the directory where i can find the logs.

Thank you guys in advance!

**Comment by johnnykv** [comment]
Hi,

There is no credentials - it's all a honeypot :).

You should be able to find log files in the directory where you started Heralding from.

**Comment by amannayyar1** [comment]
@johnnykv Thanks for the quick reply I appreciate it,
So to clarify this is just logging the attempts thrown at the different ports such as ssh or HTTP etc.... but no login can be complete just low interaction honeypot for credentials - I appreciate this its awesome!

And the last question - can the localhost IP be changed or does it have to remain as a localhost IP?

thanks in advance, I appreciate it!
Aman.

**Comment by amannayyar1** [comment]
@johnnykv Thanks for the quick reply I appreciate it,
So to clarify this is just logging the attempts thrown at the different ports such as ssh or HTTP etc.... but no login can be complete just low interaction honeypot for credentials - I appreciate this its awesome!

And the last question - can the localhost IP be changed or does it have to remain as a localhost IP?

thanks in advance, I appreciate it!
Aman.

**Comment by johnnykv** [comment]
No problem.

Not exactly sure what you mean in regards to the localhost ip. Please elaborate :)

**Comment by amannayyar1** [comment]
@johnnykv hello there,

So when activated the honeypot, and throwing login attempts its all done on the localhost ip address which is 127.0.0.1 is it possible to change that ip so i can attack the honeypot from another machine if so where can i do this? 

Thanks again, Aman

**Comment by johnnykv** [comment]
The honeypot should listen on all interfaces by default. You might have a firewall blocking - or maybe you are behind NAT?

**Comment by amannayyar1** [comment]
@johnnykv okay thanks i appreciate your help! It works now!
My final question is that as i have installed through docker is the only way i can view the log file is if i do:
Sudo docker exec -it - bash 
or is there another way to view the logs

Thank you so much johnny you have made a splendid honeypot here!

**Comment by amannayyar1** [comment]
@johnnykv okay thanks i appreciate your help! It works now!
My final question is that as i have installed through docker is the only way i can view the log file is if i do:
Sudo docker exec -it - bash
or is there another way to view the logs

Thank you so much johnny you have made a splendid honeypot here!
