### ISSUE TITLE
b64decode errors with incorrect padding on smtp module

### ISSUE THREAD

**Issue by shinji257** [johnnykv/heralding#18]
Got this error while trial running the module.

`error: uncaptured python exception, closing channel <heralding.capabilities.smtp.SMTPChannel connected 59.xxx.xxx.170:23396 at 0x7fc8d281a3b0> (<type 'exceptions.TypeError'>:Incorrect padding [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|449] [/usr/lib/python2.7/asynchat.py|handle_read|165] [/usr/local/lib/python2.7/dist-packages/heralding/capabilities/smtp.py|found_terminator|219] [/usr/local/lib/python2.7/dist-packages/heralding/capabilities/smtp.py|smtp_AUTH|131] [/usr/lib/python2.7/base64.py|b64decode|78])
`

EDIT: Inbound IP censored.

**Comment by johnnykv** [comment]
Can you provide a bit more details on this? Do you know what data was sent?

**Comment by shinji257** [comment]
No as I do not know if I have a means of actually capturing the live traffic at all unless I can do it via iptables during redirect.

All I can do is provide you with the configuration (as far as I know of it)
Host: Linode -- Unknown base configuration.  KVM virtualization
KVM "Host" system.  Ubuntu 14.04.
LXC "Guest" system.  Ubuntu 16.10 dev branch

iptables filter configuration redirect China inbound traffic to LXC container.
sudo /sbin/iptables -t nat -I PREROUTING -i eth0 -m set --match-set geoblock src -j DNAT --to 10.0.3.78

10.0.3.78 was an internal container IP that housed the services.  geoblock set is a list of known China source ip subnets so if they got on that list they were re-routed.  Port 22 attempts went there.  If there is a way to log traffic with this setup then I'll do it.

In the meantime I might see if it is possible to log traffic on the veth that is created using a common tool.

**Comment by johnnykv** [comment]
Thanks, I see the problem.

**Comment by johnnykv** [comment]
@shinji257 is is correct that it was only the current SMTP session that failed? ie. Heralding continued accepting new connections?

**Comment by shinji257** [comment]
Correct.  It continued accepting new connections beyond throwing that error.

**Comment by johnnykv** [comment]
fixed, the package should be available on pypi in a few mins.
