### ISSUE TITLE
Implement RDP capability

### ISSUE THREAD

**Issue by glaslos** [johnnykv/heralding#25]

**Comment by johnnykv** [comment]
Reference notes for future implementation:
https://wiki.wireshark.org/RDP
http://download.microsoft.com/download/9/5/e/95ef66af-9026-4bb0-a41d-a4f81802d92c/[MS-RDPBCGR].pdf

**Comment by DeveshChande** [comment]
Just leaving this here, as the second link is not functioning.
https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-RDPBCGR/%5bMS-RDPBCGR%5d.pdf
