### ISSUE TITLE
How to use systemd with Heralding?

### ISSUE THREAD

**Issue by dwasserm** [johnnykv/heralding#27]
Hi all,

I'm trying to use systemd with Heralding on Ubuntu 16.04 in order to run it as a service instead of just an adhoc Python script but running into a few problems:

1. Systemd wants to run Heralding in the foreground and I can't get it to work properly if I append `&` to the `ExecStart` stanza
2. The service quits after a little while and complains of a timeout error, even though the Python script is still running. For some reason the service keeps restarting.
`Job for heralding.service failed because a timeout was exceeded. See "systemctl status heralding.service" and "journalctl -xe" for details.`
```
$ ps -ef | grep [h]eralding
nobody    5206     1  0 20:30 ?        00:00:00 /usr/bin/python /usr/local/bin/heralding
```

Here is my unit file for Heralding that I made up. It is probably incorrect...
```
$ systemctl cat heralding.service 
# /etc/systemd/system/heralding.service
[Unit]
Description=Herlading Credentials Catching Honeypot
Documentation=https://github.com/johnnykv/heralding
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/python /usr/local/bin/heralding
WorkingDirectory=/opt/heralding/
Restart=on-failure
#TimeoutSec=300

[Install]
WantedBy=multi-user.target
```

Can anyone help out or share their own unit file for Heralding?

**Comment by johnnykv** [comment]
Below is the unit file i use myself, remember to replace the variables :-).
```
[Unit]
Description = heralding
After = network.target

[Service]
Type=simple
WorkingDirectory={{ HERALDING_WORK_DIR }}
Environment=VIRTUAL_ENV="{{ HERALDING_VIRTUALENV }}"
Environment=PATH="$VIRTUAL_ENV/bin:$PATH"
ExecStart={{ HERALDING_VIRTUALENV }}/bin/heralding
ExecReload=/bin/kill -s TERM $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
Restart=on-failure

[Install]
WantedBy = multi-user.target
```

**Comment by dwasserm** [comment]
Thanks! It seems to be working now. I guess the `type` was the main issue.

Should I set up Heralding with a virtual environment and if so, how?

**Comment by johnnykv** [comment]
I always recommend setting up virtuel environments for python projects. Keeps the system python clean.

**Comment by dwasserm** [comment]
How would I do that? Might be useful to add the steps to the readme 👍

**Comment by dwasss** [comment]
@johnnykv Heralding has been updated since the beginning of this year. I just upgraded from 0.1.15 to 0.2.1. Are you using the same systemd service? Is there another way to run Heralding in the background/non-interactively?

**Comment by johnnykv** [comment]
@dwasss Thanks for the feedback, Heralding has sene some crazy good code changes the last fem months. Seems like we need to test the systems unit again. Could you raise this as a new issue with as much details as possible?

**Comment by dwasss** [comment]
OK done, see https://github.com/johnnykv/heralding/issues/59.
