### ISSUE TITLE
How to use systemd with Heralding? part 2

### ISSUE THREAD

**Issue by dwasss** [johnnykv/heralding#59]
Continued from https://github.com/johnnykv/heralding/issues/27

Hi all,

I'm trying to use systemd with Heralding 0.2.1 on Ubuntu 16.04 in order to run it as a service instead of just an adhoc Python script but running into a few problems. I have Python and Python3, but uninstalled the Python 2.7 version of Heralding.

Here is my unit file for Heralding that I created based on @johnnykv's version.
```
$ systemctl cat heralding.service 
# /etc/systemd/system/heralding.service
[Unit]
Description=heralding
Documentation=https://github.com/johnnykv/heralding
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/heralding/
ExecStart=/usr/bin/python3 /opt/heralding/bin/heralding
ExecReload=/bin/kill -s TERM $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target 
```

But I am getting errors and it won't start up (from syslog):
```
Aug 29 18:09:58 server python3[6249]: Traceback (most recent call last):
Aug 29 18:09:58 server python3[6249]:   File "/opt/heralding/bin/heralding", line 23, in <module>
Aug 29 18:09:58 server python3[6249]:     import heralding
Aug 29 18:09:58 server python3[6249]: ImportError: No module named 'heralding'
Aug 29 18:09:58 server systemd[1]: heralding.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 18:09:58 server systemd[1]: heralding.service: Unit entered failed state.
Aug 29 18:09:58 server systemd[1]: heralding.service: Failed with result 'exit-code'.
Aug 29 18:09:58 server systemd[1]: heralding.service: Service hold-off time over, scheduling restart.
Aug 29 18:09:58 server systemd[1]: Stopped heralding.
Aug 29 18:09:58 server systemd[1]: heralding.service: Start request repeated too quickly.
Aug 29 18:09:58 server systemd[1]: Failed to start heralding.
```

Looks like something to do with the `ExecStart`. Is anyone else using systemd?

**Comment by johnnykv** [comment]
Looking at the error `ImportError: No module named 'heralding'` it seems like heralding is not installed in the python environment you are running. 
Is heralding installed systemwide or in a virtual environment?

**Comment by dwasss** [comment]
I followed the install instructions in the [README](https://github.com/johnnykv/heralding/blob/master/README.rst) so I guess system-wide?

**Comment by dwasss** [comment]
@johnnykv 
I think I might just have to start over. Can you explain the steps to set up Heralding in a virtualenv? Also, the Readme might need to be updated to use pip3 commands, right?

**Comment by dwasss** [comment]
I got it working. I will submit a readme soon but in the meantime, here is my service definition file:

```
$ systemctl cat heralding.service 
# /etc/systemd/system/heralding.service
[Unit]
Description=heralding
Documentation=https://github.com/johnnykv/heralding
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/user/heralding/
Environment=VIRTUAL_ENV="/home/user/heralding/heralding-env/"
Environment=PATH="$VIRTUAL_ENV/bin:$PATH"
ExecStart=/home/user/heralding/heralding-env/bin/heralding
ExecReload=/bin/kill -s TERM $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
