### ISSUE TITLE
question about error

### ISSUE THREAD

**Issue by dpicollege** [johnnykv/heralding#60]
Hello,
when i try to install this project. i face this problem""Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AXXE1Y/aiosmtpd/"" any solution?

another request is add hpfeeds to this project

**Comment by johnnykv** [comment]
No sure about the aiosmtpd error, maybe @kajojify could chime in on this?

Regarding hpfeeds, please raise this as a separate feature request.

**Comment by kajojify** [comment]
Hello! Try to use `pip3 install heralding` istead of the variant from readme. Make sure you use Python 3.5 or higher.

**Comment by kajojify** [comment]
Hi! Is the problem still relevant for you?

**Comment by dpicollege** [comment]
it's not working!

**Comment by dwasss** [comment]
I agree with @dpicollege, updated installation would be helpful.

**Comment by dwasss** [comment]
@dpicollege I created step by step installation instructions, see https://github.com/johnnykv/heralding/blob/master/INSTALL.md.

**Comment by dpicollege** [comment]
thanks indeed. i will install and inform you what happen.

**Comment by johnnykv** [comment]
Please reopen if this is still a issue.
