### ISSUE TITLE
feature request: add hpfeeds support

### ISSUE THREAD

**Issue by dpicollege** [johnnykv/heralding#63]
Hello,
please add hpfeeds protocol support

**Comment by johnnykv** [comment]
Preliminary hpfeeds support has been added on the hpfeeds branch - if you test it out and it works, I will merge it into master.

**Comment by johnnykv** [comment]
@dpicollege hpfeeds support has been merged into master. Please test it and report back.

**Comment by johnnykv** [comment]
@dpicollege did you have a chance to test this?
