### ISSUE TITLE
attempts not logged unless -v is used

### ISSUE THREAD

**Issue by mrkiwi-nz** [johnnykv/heralding#66]
On a live-usb version of Ubuntu 17.04 I followed this [guide](https://github.com/johnnykv/heralding/blob/master/INSTALL.md)
however the only things logged was the starting of each service.
Adding -v to the command like such;
`sudo ./heralding-env/bin/heralding -v`
added a bunch of other lines to the log, including the usernames and passwords attempted.

Is this the expected result?

**Comment by andrewmichaelsmith** [comment]
Did you check heralding_activity.log?

**Comment by johnnykv** [comment]
@andrewmichaelsmith is right, only system level logs (mostly warnings and startup stuff) are emitted to stdout. For the credentials you need to look in the heralding_activity.log file.
