### ISSUE TITLE
Error messages during installation/running of heralding

### ISSUE THREAD

**Issue by dhu041** [johnnykv/heralding#69]
1. I tried to install and run heralding on an Ubuntu (16.04) machine with Python 2.7.12. Installation of the required packages and heralding succeeded but it doesn't run due to missing python module named "_curses". I have been searching for various solutions and installed many recommended packages that claim to contain the _curses module but still getting the same error message.  

2. As an option I also tried it on a python virtual environment (Python version is 3.6.3) on Ubuntu 16.04 machine. I followed the steps mentioned at https://github.com/johnnykv/heralding/blob/master/INSTALL.md
After installing the requirements, when I run "pip install heralding" it generates an error message about missing file named "requirements-test.txt" while the file already exists.  
The output is -
Collecting heralding
  Downloading Heralding-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eu278hb4/heralding/setup.py", line 20, in <module>
        tests_require=open('requirements-test.txt').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements-test.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eu278hb4/heralding/

Can you help to fix these problems?

**Comment by kajojify** [comment]
@dhu041 Hello!
1) Heralding supports only Python 3.5+ versions now. 
For Heralding usage:
-  on the machine with Python 2, please use version **0.1.17** or earlier. 
-  on the machine with Python 3 < 3.5, please use version **0.2.0**. 

2) I reproduced your issue. 
After some digging, I found out that the problem is probably in [_pypi_ version](https://pypi.python.org/pypi/heralding) of Heralding. 
I downloaded Heralding from there, extracted an archive and didn't find `requirements-test.txt` there. 
I hope @johnnykv will fix it.

**Comment by dhu041** [comment]
Thanks @kajojify !

**Comment by johnnykv** [comment]
@kajojify Uhm, why is requirements-test.txt needed in the package? Maybe @andrewmichaelsmith can enlighten us the specifics of this file?

**Comment by kajojify** [comment]
@johnnykv As I understood, postgresql tests need additional module psycopg2. Since we don't want to add extra dependencies to requirements.txt, this dependency was put to separate file. 
New line in setup.py:
```tests_require=open('requirements-test.txt').read()```
This file lets us use specific requirements for tests.

**Comment by johnnykv** [comment]
Closed with 0.2.4.
