### ISSUE TITLE
Logging issue - auth_type

### ISSUE THREAD

**Issue by dwasss** [johnnykv/heralding#75]
The `auth_type` field as documented in the readme is actually not implemented. It is supposed to be logged in log_auth.csv according to the readme, but that only has the following fields: `timestamp,auth_id,session_id,source_ip,source_port,destination_ip,destination_port,protocol,username,password`.

> log_auth.csv
>
>This log file contains information for all authentication attempts where it was possible to log a username and plaintext password. Log entries will appear in this file as soon as the password has been transmitted.
>
>$ tail log_auth.csv >timestamp,auth_id,auth_type,session_id,source_ip,source_port,destination_port,protocol,username,password 2016-03-12 20:35:02.258198,192.168.2.129,51551,23,telnet,bond,james 2016-03-12

**Comment by johnnykv** [comment]
The auth_type is not well implemented in the code, it has little to no use with the current implementation (search for add_auth_attempt and look at the _type parameter) in the source code. I will update the readme (until someone implemented auth_type properly).
