### ISSUE TITLE
Implement mysql/mariadb capability

### ISSUE THREAD

**Issue by otih** [johnnykv/heralding#76]

**Comment by realsdx** [comment]
I would like to work on this issue.

**Comment by kajojify** [comment]
@realsdx Go ahead! Good luck! Once I also implemented it, but we decided that we didn't need hashed password at that moment.
This will definetely help you -> https://mariadb.com/kb/en/library/connection/#initial-handshake-packet

**Comment by realsdx** [comment]
Thanks! I will start working on it.

**Comment by johnnykv** [comment]
This MySQL capability has been introduced in master as of today.
