### ISSUE TITLE
enum34 in requirements

### ISSUE THREAD

**Issue by slavkoja** [johnnykv/heralding#79]
You have in readme, that python 3.5+ is required, but in `requirements.txt` is `enum34` mentioned. AFAIK, it backports the `enum` module into python <3.4 and it is in standard library for 3.4+. Is it still needed?

BTW, in readme you have:
```
pip install -r requirements.txtri
```
Is the `requirements.txtri` right?

**Comment by johnnykv** [comment]
You are right, thanks for the headsup. Fixed in the next commit.
