### ISSUE TITLE
Log user agent for http

### ISSUE THREAD

**Issue by t3chn0m4g3** [johnnykv/heralding#85]
For statistical purposes it would be great if it was possible to also log (where possible) user agent string into `auth.csv`

**Comment by johnnykv** [comment]
auth.csv is meant to be simple and streamlined, only authentication stuff will be logged into that file. That said, for fingerprinting (and statistical) purposes I would be interesting to log additional information for each protocol. Not sure how to proceed on this...

**Comment by DeveshChande** [comment]
Logging the user-agent, geolocation and heralding-version seems to be a good starting point. Besides Python, are other programming languages a viable solution? Regardless, I'd like to start working on this!

**Comment by q2dg** [comment]
Sorry if it's offtopic, but implementing a ELK connector to delegate the storage of all this information anywhere else could be a good idea?

**Comment by t3chn0m4g3** [comment]
@q2dg You should have a look at [T-Pot](https://github.com/dtag-dev-sec/tpotce/tree/master/docker/heralding).

**Comment by q2dg** [comment]
@t3chn0m4g3 Ooh, thanks a lot!

**Comment by t3chn0m4g3** [comment]
@q2dg Welcome 😃

**Comment by johnnykv** [comment]
I agree with @t3chn0m4g3.

**Comment by johnnykv** [comment]
Issue merged into #91 (Logging of aux data).

**Comment by johnnykv** [comment]
user agent it now logged in an auxiliary log file for http.

**Comment by johnnykv** [comment]
complete session info (including user agent) is not logged to log_session.json.
