### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by DeveshChande** [johnnykv/heralding#92]
Steps to replicate :

1. Start heralding.

2. Copy image url address (of any image, here is an example) :

https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12193133/German-Shepherd-Puppy-Fetch.jpg

3. Open web browser ( I’m using Chrome ).

4. Connect to `0.0.0.0:80` for HTTP connection.

5. Now, enter the image url as the username in login-page. Put anything for password.

6. The page crashes. `[ERR-EMPTY-RESPONSE]`

7. Now, open any other web browser. For example, Safari. Heralding works fine here. Chrome will never load `0.0.0.0` until it is restarted.

The error message given is : `ValueError : Too many values to unpack (expected 2)`.

As pointed out by @realsdx, ":" is the issue.
File : https://github.com/johnnykv/heralding/blob/master/heralding/capabilities/http.py
Even if username:password is entered in "username" field, this will still create problems.

**Comment by kajojify** [comment]
An error occurs because of this line -> https://github.com/johnnykv/heralding/blob/master/heralding/capabilities/http.py#L62

`dec_uname_pwd` contains something like "test:123:password", `split` method breaks it into 3 parts by ":" separator, so there are 3 strings, but 2 variables. That's why we have an error.

**Comment by DeveshChande** [comment]
I’d like to apologize for the delay, I had exams. Coming to the above issue, [RFC 2617](https://tools.ietf.org/html/rfc2617#section-2) and [RFC 7617](https://tools.ietf.org/html/rfc7617#section-4)  indicate that valid username’s cannot contain the character colon (“:”).

Thus, we can simply split the string that is passed via the http authentication protocol. This raises two questions :

1. What if the username contains a colon?

2. What if the password contains a colon?

To answer the first question, there simply isn’t a one-size-fits-all solution, because the usernames passed could be of the form “username:u1”, “username::u2”, “username:::”. Thus, we can offer guaranteed solutions for 2 or 3 colons present in the username, but after that the cases cannot be handled automatically. They will require a human-touch, so to speak. So, I think logging dec_uname_pwd in the place of password will be useful as the user of the honeypot can compare and see what was passed.

Coming to the second question, it is extremely easy to handle a password.
What do you think? @johnny and @kajoj.

**Comment by kajojify** [comment]
> I’d like to apologize for the delay, I had exams.
Everything is ok. All we have some business at university/work :) 

I think, that we should follow RFCs and consider colon usage as an error. 
But I also think we should log `dec_uname_pwd`, probably only in _verbose_ mode. 
@johnnykv?

**Comment by johnnykv** [comment]
Uhm, from the RFC:

>    Furthermore, a user-id containing a colon character is invalid, as
>    the first colon in a user-pass string separates user-id and password
>    from one another; text after the first colon is part of the password.
>    User-ids containing colons cannot be encoded in user-pass strings.

So...  I guess this means john::bond is valid and should decode to username=john, password=:bond

**Comment by DeveshChande** [comment]
I've almost solved this but I face the following dilemma : 

If the user attempts to login via **only** the username field, for the text "john::bond", then heralding will see it as username = john and password = :bond:.

This is going to conflict with the scenario wherein the user inputs into the username field = john and password field = :bond:.

Both will have the same output but input is different. As such, logging of data will not be accurate.

Is there a way we can pull the username and password fields individually? Or are we always assuming that both fields will be filled?

**Comment by kuax** [comment]
It's the browser who does the encoding and sends the request, so there is no way of receiving the two fields separately...
As @johnnykv cited:

> text after the first colon is part of the password

I guess this is true also for "real" web servers: if you input `john::bond` in the username field and provide no password, the authentication backend will likely try to authenticate user `john` with password `:bond:`. Would be nice to set up a little test server to confirm this :)

**Comment by johnnykv** [comment]
So, where are we on this one? But or feature? :-)

**Comment by realsdx** [comment]
I think it's feature ;-)
