### ISSUE TITLE
Fix/update test environment

### ISSUE THREAD

**Issue by johnnykv** [johnnykv/heralding#94]
The test for 3.5.0 is failing:

https://travis-ci.org/johnnykv/heralding/jobs/507151225

My hunch is that it’s because of some issue that was fixed in 3.5.1.

3.5 is pretty old, therefore the Travis config should be fixed so that we test all python release starting from 3.6.4.

**Comment by realsdx** [comment]
Should we make it up to the latest stable version 3.7.2 ? or older

**Comment by realsdx** [comment]
Seems like travis still dosen't have python 3.7.

**Comment by johnnykv** [comment]
Then pick the highest version that Travis supports.

**Comment by kajojify** [comment]
Travis should support Python 3.7 -> https://docs.travis-ci.com/user/languages/python/#development-releases-support
